import { Resource } from './types';

export const MOCK_RESOURCES: Resource[] = [
  {
    id: '1',
    title: '沙丘2 (2024) [2160p] [HDR]',
    year: 2024,
    quality: '4K',
    tags: ['HDR', 'Remux'],
    size: '24.5GB',
    sourceCount: 115,
    sourceName: '电影大师',
    date: '2小时前',
    posterUrl: 'https://picsum.photos/seed/dune2/200/300',
    type: 'movie',
    description: '保罗·厄崔迪与契妮和弗雷曼人联合起来，对摧毁他家族的阴谋者展开复仇之战。',
    platform: '115网盘',
    shareLink: 'https://115.com/s/sw3b2k...',
    accessCode: 'a8b4',
    saved: false,
  },
  {
    id: '2',
    title: '三体 - 第一季全集 - 多语言',
    year: 2024,
    quality: 'S01',
    tags: ['Web-DL', '多字幕'],
    size: '18.2GB',
    sourceCount: 89,
    sourceName: '科幻迷',
    date: '昨天',
    posterUrl: 'https://picsum.photos/seed/3body/200/300',
    type: 'series',
    description: '1960年代中国的一个关键决定跨越时空回响至今天的科学家群体，迫使他们面对人类最大的威胁。',
    platform: '夸克云盘',
    shareLink: 'https://pan.quark.cn/s/3body...',
    accessCode: 'x9y2',
    saved: false,
  },
  {
    id: '3',
    title: '奥本海默 (2023) IMAX 增强版 Remux',
    year: 2023,
    quality: '4K',
    tags: ['IMAX', 'DTS-HD'],
    size: '64GB',
    sourceCount: 230,
    sourceName: '诺兰粉',
    date: '3天前',
    posterUrl: 'https://picsum.photos/seed/oppenheimer/200/300',
    type: 'movie',
    description: '美国科学家J·罗伯特·奥本海默及其在原子弹研发中的故事。',
    platform: '迅雷云盘',
    shareLink: 'magnet:?xt=urn:btih:oppenheimer...',
    saved: true,
  },
  {
    id: '4',
    title: '地球脉动 III - 4K 杜比视界',
    year: 2023,
    quality: '纪录片',
    tags: ['杜比视界', '全景声'],
    size: '42GB',
    sourceCount: 115,
    sourceName: '自然爱好者',
    date: '1周前',
    posterUrl: 'https://picsum.photos/seed/planet/200/300',
    type: 'doc',
    description: '大卫·爱登堡呈现的纪录片系列，探索地球上最壮观的栖息地及其中的野生动物。',
    platform: '115网盘',
    shareLink: 'https://115.com/s/nature3...',
    accessCode: 'tree',
    saved: false,
  }
];

export const SEARCH_FILTERS = [
  { id: 'all', label: '全部', icon: 'apps' },
  { id: 'baidu', label: '百度', icon: 'cloud_circle' },
  { id: 'aliyun', label: '阿里', icon: 'cloud' },
  { id: 'quark', label: '夸克', icon: 'flight', rotateIcon: true },
  { id: 'tianyi', label: '天翼', icon: 'cloud_queue' },
  { id: 'uc', label: 'UC', icon: 'language' },
  { id: 'mobile', label: '移动', icon: 'signal_cellular_alt' },
  { id: '115', label: '115', icon: 'folder_shared' },
  { id: 'pikpak', label: 'PikPak', icon: 'play_circle' },
  { id: 'xunlei', label: '迅雷', icon: 'bolt' },
  { id: '123', label: '123', icon: 'filter_1' },
  { id: 'magnet', label: '磁力', icon: 'share' },
  { id: 'ed2k', label: '电驴', icon: 'link' },
];